name: found_and_loading
description: "InfoEducatie Open 2025 - Contras Adrian"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  ar_flutter_plugin_2:
    path: ./ar_flutter_plugin_2

  flame: ^1.10.0

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.0.0
  camera: ^0.10.0+4
  vector_math: ^2.1.0
  permission_handler: ^11.3.1

  image_picker: ^1.0.4
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  just_audio: ^0.9.36
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/music/halloween.mp3
    - assets/images/player/
    - assets/music/gunshot.mp3 # my favorite music rn
    - assets/images/bullet/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


flutter_native_splash:
  color: "#4B2E20"
  image: assets/images/icon.png
  android: true
  ios: true